
package Forms;

import Entidades.Ferro;
import Models.ModelTabela;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form FormPrincipal
     */
    DefaultTableModel tabela;
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbFerro = new javax.swing.JTable();
        btAddFerro = new javax.swing.JButton();
        btEdtFerro = new javax.swing.JButton();
        btDelFerro = new javax.swing.JButton();
        btCalcular = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTabela = new javax.swing.JMenu();
        addFerro = new javax.swing.JMenuItem();
        editFerro = new javax.swing.JMenuItem();
        delFerro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbFerro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tbFerro);

        btAddFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/add.png"))); // NOI18N
        btAddFerro.setText("Add Ferro");
        btAddFerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFerroActionPerformed(evt);
            }
        });

        btEdtFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/editar.png"))); // NOI18N
        btEdtFerro.setText("Editar");
        btEdtFerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdtFerroActionPerformed(evt);
            }
        });

        btDelFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/excluir.png"))); // NOI18N
        btDelFerro.setText("Excluir");
        btDelFerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelFerroActionPerformed(evt);
            }
        });

        btCalcular.setBackground(new java.awt.Color(0, 50, 0));
        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        menuTabela.setText("Tabela");

        addFerro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        addFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/add.png"))); // NOI18N
        addFerro.setText("Add Ferro");
        addFerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFerroActionPerformed(evt);
            }
        });
        menuTabela.add(addFerro);

        editFerro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        editFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/editar.png"))); // NOI18N
        editFerro.setText("Editar Ferro");
        editFerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFerroActionPerformed(evt);
            }
        });
        menuTabela.add(editFerro);

        delFerro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        delFerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/excluir.png"))); // NOI18N
        delFerro.setText("Excluir Ferro");
        menuTabela.add(delFerro);

        jMenuBar1.add(menuTabela);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btAddFerro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEdtFerro)
                        .addGap(33, 33, 33)
                        .addComponent(btDelFerro)
                        .addGap(18, 18, 18)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCalcular)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddFerro)
                    .addComponent(btEdtFerro)
                    .addComponent(btDelFerro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btCalcular)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       montarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void addFerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFerroActionPerformed
       FormAddFerro faf = new FormAddFerro();
       faf.setVisible(true);
    }//GEN-LAST:event_addFerroActionPerformed

    private void btAddFerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFerroActionPerformed
       FormAddFerro faf = new FormAddFerro();
       faf.setModal(true);
       faf.setVisible(true);
    }//GEN-LAST:event_btAddFerroActionPerformed

    private void btEdtFerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdtFerroActionPerformed
        if (tbFerro.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Item para esta ação");
        } else {
            FormAddFerro ff = new FormAddFerro();
            ff.f.setId((Long) tbFerro.getValueAt(tbFerro.getSelectedRow(), 0));
            ff.f.setTipo((String) tbFerro.getValueAt(tbFerro.getSelectedRow(), 1));
            ff.f.setDiametro((Double) tbFerro.getValueAt(tbFerro.getSelectedRow(), 2));
            ff.f.setPeso_metro((Double) tbFerro.getValueAt(tbFerro.getSelectedRow(), 3));
            ff.setModal(true);
            ff.setVisible(true);
        }
    }//GEN-LAST:event_btEdtFerroActionPerformed

    private void editFerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFerroActionPerformed
        if (tbFerro.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Item para esta ação");
        } else {
            FormAddFerro ff = new FormAddFerro();
            ff.f.setId((Long) tbFerro.getValueAt(tbFerro.getSelectedRow(), 0));
            ff.f.setTipo((String) tbFerro.getValueAt(tbFerro.getSelectedRow(), 1));
            ff.f.setDiametro((Double) tbFerro.getValueAt(tbFerro.getSelectedRow(), 2));
            ff.f.setPeso_metro((Double) tbFerro.getValueAt(tbFerro.getSelectedRow(), 3));
            ff.setModal(true);
            ff.setVisible(true);
        }
    }//GEN-LAST:event_editFerroActionPerformed

    private void btDelFerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelFerroActionPerformed
        ModelTabela mt = new ModelTabela();
        EntityManager em = ModelTabela.openDB();
        if (tbFerro.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Item para esta ação");
        } else {
            
        }
    }//GEN-LAST:event_btDelFerroActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
       
    }//GEN-LAST:event_btCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    private void montarTabela() {
        tbFerro.setModel(new DefaultTableModel(
                new Object[][]{}, new String[]{"ID","TIPO", "DIAMETRO", "PESO/M"}
        ));
        tabela = (DefaultTableModel) tbFerro.getModel();
        ModelTabela mt = new ModelTabela();
        for (Ferro f : mt.listaFerro()) {
            tabela.addRow(new Object[]{f.getId(),f.getTipo(), f.getDiametro(), f.getPeso_metro()});
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addFerro;
    private javax.swing.JButton btAddFerro;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btDelFerro;
    private javax.swing.JButton btEdtFerro;
    private javax.swing.JMenuItem delFerro;
    private javax.swing.JMenuItem editFerro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuTabela;
    private javax.swing.JTable tbFerro;
    // End of variables declaration//GEN-END:variables
}
